---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - transformations.transformations.go
  resources:
  - transformations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transformations.transformations.go
  resources:
  - transformations/finalizers
  verbs:
  - update
- apiGroups:
  - transformations.transformations.go
  resources:
  - transformations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
