# permissions for end users to view transformations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: transformation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: transformation-operator
    app.kubernetes.io/part-of: transformation-operator
    app.kubernetes.io/managed-by: kustomize
  name: transformation-viewer-role
rules:
- apiGroups:
  - transformations.transformations.go
  resources:
  - transformations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transformations.transformations.go
  resources:
  - transformations/status
  verbs:
  - get
