---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testcm
data:
  key: cool value
---
apiVersion: transformations.transformations.go/v1alpha1
kind: Transformation
metadata:
  labels:
    app.kubernetes.io/name: transformation
    app.kubernetes.io/instance: transformation-sample
    app.kubernetes.io/part-of: transformation-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: transformation-operator
  name: transformation-sample
spec:
  target:
    kind: ConfigMap
    name: test-transform
    labels:
      tets: test
    annotations:
      tets: test
  template:
    test: |
      This is an example of a long template with '{{ .testcm.key }}' extracted from a configmap
  sources:
    - kind: ConfigMap
      name: testcm
